package com.nicequestion.donatas.adf.controller;

import com.nicequestion.donatas.model.Person;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;


/**
 * Task flow controller for the CRUD Bean data control sample
 * 
 * @author Donatas Valys
 */
public class CRUDPersonsTaskFlowController {
    
    private List<Person> personList;
    
    public CRUDPersonsTaskFlowController() {
        super();
    }


    /**
     * Task flow initializer - init some test data
     */
    public void init() {
        initSampleData();
    }

    public void setPersonList(List<Person> personList) {
        this.personList = personList;
    }

    public List<Person> getPersonList() {
        return personList;
    }


     /** Copy person by using copy constructor
      * 
      * @param person person to copy
      */
    public void copyPerson(Person person) {  
         personList.add(new Person(person));
    }

    /**
     * Put some sample data generated by http://www.generatedata.com/#generator
     */
    private void initSampleData() {
        personList = new ArrayList<Person>();
        
        personList.add(new Person() {
            {
                setNumber(959);
                setFirstName("Imani");
                setLastName("Baldwin");
                setBirthday(parseDate("Mar 14, 1944"));
            }
        });
        personList.add(new Person() {
            {
                setNumber(477);
                setFirstName("Bertha");
                setLastName("Hopper");
                setBirthday(parseDate("Nov 5, 1955"));
            }
        });
        personList.add(new Person() {
            {
                setNumber(803);
                setFirstName("Rhiannon");
                setLastName("Riddle");
                setBirthday(parseDate("Sep 25, 1941"));
            }
        });
        personList.add(new Person() {
            {
                setNumber(365);
                setFirstName("Basia");
                setLastName("Garcia");
                setBirthday(parseDate("Sep 6, 1988"));
            }
        });
        personList.add(new Person() {
            {
                setNumber(342);
                setFirstName("Byron");
                setLastName("Britt");
                setBirthday(parseDate("Apr 29, 1967"));
            }
        });
    }
    
    private Date parseDate(String dateString) {
        try {
            return sdf.parse(dateString);
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    private SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH);
    
}
